const { chromium } = require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES + '/playwright');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
  await page.screenshot({path:'qa-dashboard.png',fullPage:true});
  await page.click('#newJobHero');
  await page.fill('[name=customerName]','Sample Customer');
  await page.fill('[name=projectAddress]','123 Sample Street, Cincinnati, OH');
  await page.click('[data-step="2"]');
  await page.fill('[name=description]','Repair and finish the damaged interior wall area.');
  await page.fill('[data-f=description]','Drywall repair and finish');
  await page.fill('[data-f=qty]','1');
  await page.fill('[data-f=rate]','850');
  await page.waitForTimeout(600);
  await page.screenshot({path:'qa-editor-mobile.png',fullPage:true});
  const total=await page.textContent('#grandTotal');
  if(total!=='$850.00') throw new Error('Total calculation failed: '+total);
  if(errors.length) throw new Error(errors.join('\n'));
  console.log('UI_CHECK_OK '+total);
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
